name: Publish pg2any-lib to crates.io

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish pg2any-lib to crates.io
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev pkg-config libssl-dev

    - name: Extract version from tag
      id: get_version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Verify tag matches Cargo.toml version
      run: |
        CARGO_VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/.*= "//' | sed 's/".*//')
        TAG_VERSION="${{ steps.get_version.outputs.version }}"
        echo "Cargo.toml version: $CARGO_VERSION"
        echo "Git tag version: $TAG_VERSION"
        if [ "$CARGO_VERSION" != "$TAG_VERSION" ]; then
          echo "Error: Version mismatch between Cargo.toml ($CARGO_VERSION) and git tag ($TAG_VERSION)"
          exit 1
        fi

    - name: Run tests
      working-directory: pg2any-lib
      run: cargo test --lib --verbose

    - name: Dry run publish
      working-directory: pg2any-lib
      run: cargo publish --dry-run -p pg2any_lib
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish to crates.io
      working-directory: pg2any-lib
      run: cargo publish -p pg2any_lib
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    # - name: Create GitHub Release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.get_version.outputs.tag }}
    #     release_name: Release ${{ steps.get_version.outputs.tag }}
    #     body: |
    #       ## Changes
          
    #       See [CHANGELOG.md](https://github.com/isdaniel/pg2any/blob/main/CHANGELOG.md) for details.
          
    #       ## Crates.io
          
    #       The `pg2any_lib` crate has been published to crates.io:
    #       - [`pg2any_lib` v${{ steps.get_version.outputs.version }}](https://crates.io/crates/pg2any_lib/${{ steps.get_version.outputs.version }})
          
    #       ## Installation
          
    #       Add to your `Cargo.toml`:
    #       ```toml
    #       [dependencies]
    #       pg2any_lib = "${{ steps.get_version.outputs.version }}"
    #       ```
    #     draft: false
    #     prerelease: false
